// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/krispogram.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Post) Validate() error {
	return nil
}
func (this *NewPost) Validate() error {
	return nil
}
func (this *GetPostByIdReq) Validate() error {
	return nil
}
func (this *GetPostsByAuthorIdReq) Validate() error {
	return nil
}
func (this *GetPostsByAuthorIdResp) Validate() error {
	for _, item := range this.Posts {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Posts", err)
			}
		}
	}
	return nil
}
